# Generated by Django 3.2.13 on 2022-11-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickName',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
