# Generated by Django 3.2.13 on 2022-11-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_comment_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_rate',
            field=models.CharField(choices=[(1, '★'), (1.5, '★☆'), (2, '★★'), (2.5, '★★☆'), (3, '★★★'), (3.5, '★★★☆'), (4, '★★★★'), (4.5, '★★★★☆'), (5, '★★★★★')], default='★', max_length=5),
        ),
    ]
